### ISSUE TITLE
Add an option to disable TLS certificate checks

### ISSUE THREAD

**Issue by wereHamster** [aristidb/aws#105]
Uploading an object to S3 fails about half the time (with TlsException (HandshakeFailed (Error_Protocol ("certificate has unknown CA",True,UnknownCa)))). I suspect a bug in the haskell tls package. It wouldn't be the first one that I came across.

**Comment by aviaviavi** [comment]
Just for the record, I still see this issue when trying to use this package on an ec2 instance when trying to interact with s3
