### ISSUE TITLE
Some Dynamo errors are not parsed

### ISSUE THREAD

**Issue by glasserc** [aristidb/aws#146]
I got this exception:

```
DdbError {ddbStatusCode = 400, ddbErrCode = AccessDeniedException, ddbErrMsg = ""}
```

The eventual cause was that my IAM token did not have permission to access an index on the DynamoDB table (although it had access to the table itself). I believe the DynamoDB response probably said so, but it wasn't parsed correctly, leaving ``ddbErrMsg`` empty. I believe that the reason the message wasn't parsed correctly is that some AWS error messages have message in a "message" field, and others in a "Message" field (see for example alephcloud/hs-aws-kinesis#9).

If handling all the different variants that AWS uses in their JSON doesn't appeal to you, could the message perhaps fall back to the raw JSON of the response body? That way at least a human developer could read the messages and figure out what happened.

**Comment by aristidb** [comment]
I believe I have an (untested) patch, can you take a look Ozgun? I'll make
a pull request and CC you on it shortly.


Ozgun Ataman <notifications@github.com> schrieb am Mon Dec 29 2014 at
19:39:53:

The exact error mesage should definitely be parsed and returned to the
> user. This sounds like a bug and we should take a look at it.
>
>
>
> > On Dec 29, 2014, at 1:49 PM, Ethan Glasser-Camp <
