### ISSUE TITLE
Ord on Method?

### ISSUE THREAD

**Issue by MichaelXavier** [aristidb/aws#150]
Hi! I was wondering if you'd take a PR for adding a derived Ord instance to Method. I have a use case that puts them into a Set which requires Ord. Users would face the same if they wanted to create a Map with Method keys. I can newtype wrap for now but that kind of leaks an implementation concern to the public API. Thoughts?

**Comment by tr00per** [comment]
Are you sure that you're using the right data structure? It doesn't make sense to me to add ordering to HTTP methods.

**Comment by aristidb** [comment]
Just go ahead and make a pull request:) I don't have a priori reasons for
rejecting an Ord instance there.

Artur Czajka <notifications@github.com> schrieb am Wed Feb 11 2015 at
11:39:26:

**Comment by MichaelXavier** [comment]
I actually ended up needing to roll my own Method because 1) the one in aws doesn't try to be an accurate list of valid HTTP verbs, they're (understandably) ones that aws uses internally and 2) the API I'm using actually only accepts certain combinations so a `Set Method` isn't the right choice anymore, so I don't need an Ord. I agree that there is no semantic meaning to an Ord instance. `Map` and `Set` demand Ord not for its semantics but for performance. I'll go ahead and add it to a PR and let you all decide, its a 1 liner ;)
