### ISSUE TITLE
extend StorageClass to support google nearline

### ISSUE THREAD

**Issue by joeyh** [aristidb/aws#155]
It seems that nearline needs x-amz-storage-class: NEARLINE. The StorageClass data type doesn't currently support that.

I don't know if other changes are needed to support google nearline's variant of S3, but that seems like a good first step.

(Perhaps add an | StorageClass String constructor so that the library doesn't need to be changed to use other S3 variants?)

**Comment by aristidb** [comment]
Hmm interesting, didn't know about Nearline until now. I think a "| OtherStorageClass String" is probably the best idea.

**Comment by jlebar** [comment]
It's not clear to me, but I think nearline might work if one just left off the storage-class, which it seems one can do with the current api here.  Google's storage class is per-bucket, not per-object, so at the point that you're PUT'ing an object into the bucket, it knows what storageclass you want...

**Comment by jlebar** [comment]
(But the library still needs to support *creating* buckets, so nevermind me.)

**Comment by joeyh** [comment]
Amazon just added its "Standard - IA" storage class, so might as well support it too. 

(OtherStorageClass String would let clients start using it today, without waiting for library updates.)

**Comment by bgilbert** [comment]
#176 doesn't appear to be a complete fix for Nearline support.  Google Cloud Storage configures storage classes per-bucket, not per-object, so there needs to be a way to set a non-default storage class in the PutBucket call.

**Comment by joeyh** [comment]
Benjamin Gilbert wrote:
> #176 doesn't appear to be a complete fix for Nearline support. Google Cloud
> Storage configures storage classes per-bucket, not per-object, so there needs
> to be a way to set a non-default storage class in the PutBucket call.

I have not been able to test with Google Cloud Storage yet, but a user
did, and reports that putting an object fails unless the correct storage
class is provided at put time. Specifying the STANDARD storage class for
an object put fails with InvalidArgument.

And yes, the nearline storage class has to be provided when the bucket
is created too, which this library doesn't allow. My patch only gets
part of the way there; I think it will allow at least using existing
nearline buckets in GCS.

-- 
see shy jo

**Comment by jlebar** [comment]
I'd like to test this, but it's unclear to me how one should go about doing it: When I enableremote, git annex tries to create the nearline bucket and fails, even if the bucket already exists.  Is there a way to tell it to use an existing bucket rather than to create its own, or do I need to go in and manually edit the config in my git-annex branch?

**Comment by bgilbert** [comment]
@jlebar Passing `bucket=bucketname` to `enableremote` should work.

**Comment by jlebar** [comment]
Aha, that seems to set the metadata correctly, thanks.  But I realized that I'm not yet running the 9/23 build of git annex, so I can't test yet.  :)  If I can make it work with a new build, I'll update the docs.

Thanks again.
