### ISSUE TITLE
Add upper bound to `errors` dependencies for `aws` family of packages

### ISSUE THREAD

**Issue by Gabriel439** [aristidb/aws#159]
`errors-2.0` will be switching to the use of `ExceptT` instead of `EitherT`, which may or may not break your packages.  If it will break your packages then I would recommend adding an upper bound of `errors < 2.0` to your package dependencies.

**Comment by aristidb** [comment]
Adding it to aws itself should suffice, I think, as it is the core package.

**Comment by Gabriel439** [comment]
Yeah, that would work perfectly

**Comment by aristidb** [comment]
Done.

**Comment by Gabriel439** [comment]
Don't forget to upload this to Hackage when you get the chance.  There is no hurry as I'm still a few weeks out before uploading `errors-2.0` to Hackage

**Comment by aristidb** [comment]
0.11.4 is out

Gabriel Gonzalez <notifications@github.com> schrieb am Sa., 18. Apr. 2015
um 21:28 Uhr:
