### ISSUE TITLE
Add Aws.Sqs endpoint for 'ap-southeast-2' 

### ISSUE THREAD

**Issue by tmcgilchrist** [aristidb/aws#161]
A small annoyance but there's no Endpoint available for 'ap-southeast-2' in Aws.Sqs.Core. So in using this library we end up having to build our own like so:
```
sqsEndpointApSouthEast2 :: Aws.Sqs.Endpoint
sqsEndpointApSouthEast2 = Aws.Sqs.Endpoint (BS.pack "sqs.ap-southeast-2.amazonaws.com") Aws.S3.Core.locationApSouthEast2 [Aws.S3.Core.locationApSouthEast2]
```

Perhaps the recommended way to do it but it is kinda annoying considering the endpoint is provided for EC2. Is it possible to include? Happy to do a PR for it.

**Comment by aristidb** [comment]
Of course it's possible to include

**Comment by aristidb** [comment]
Fixed in master
