### ISSUE TITLE
DynamoDB: No support for Lists and Maps?

### ISSUE THREAD

**Issue by angerman** [aristidb/aws#170]
Am I reading this right, that dynamodb does not support Lists `"L"` and Maps `"M"` types? I've looked at: Core.hs#L563, which seems to confirm this. But I'm not sure, if I'm missing something.

It this intentional?

**Comment by aristidb** [comment]
Ping @ozataman

**Comment by puffnfresh** [comment]
Took me a while to figure out why my values weren't being decoded but I found this out, too. Going to fix the problem now.
