### ISSUE TITLE
Latest aws causes test build failure under nix

### ISSUE THREAD

**Issue by dmjio** [aristidb/aws#171]
If no AWS credentials are specified can we just `return ()` on the tests? Otherwise, why force users to pay for tests to be run everytime they rebuild under nix? I don't think there is a test `sqs` server either, or test credentials provided by AWS. For dynamo we could use `dynalite`, but this assumes users have that installed.

In the `stripe-haskell` project, Stripe has a test api, w/ test keys. But if an end user doesn't specify keys, the only thing we can do is print a warning that tests weren't run and return success. This will allow services like nix to continue to build packages.

Is there another way we can handle this that anyone thinks is better?

```bash
tests/DynamoDb/Main.hs:141:16: Warning:
    In the use of ‘HTTP.withManager’
    (imported from Network.HTTP.Client, but defined in http-client-0.4.18.1:Network.HTTP.Client.Manager):
    Deprecated: "Use newManager instead"
Linking dist/build/dynamodb-tests/dynamodb-tests ...
running tests
Running 2 test suites...
Test suite sqs-tests: RUNNING...

NOTE

This test suite accesses the AWS account that is associated with
the default credentials from the credential file ~/.aws-keys.

By running the tests in this test-suite costs for usage of AWS
services may incur.

In order to actually excute the tests in this test-suite you must
provide the command line options:

    --run-with-aws-credentials

When running this test-suite through cabal you may use the following
command:

    cabal test --test-option=--run-with-aws-credentials sqs-tests

Test suite sqs-tests: FAIL
Test suite logged to: dist/test/aws-0.12.1-sqs-tests.log
Test suite dynamodb-tests: RUNNING...

NOTE

This test suite accesses the AWS account that is associated with
the default credentials from the credential file ~/.aws-keys.

By running the tests in this test-suite costs for usage of AWS
services may incur.

In order to actually excute the tests in this test-suite you must
provide the command line options:

    --run-with-aws-credentials

When running this test-suite through cabal you may use the following
command:

    cabal test --test-option=--run-with-aws-credentials dynamodb-tests

Test suite dynamodb-tests: FAIL
Test suite logged to: dist/test/aws-0.12.1-dynamodb-tests.log
0 of 2 test suites (0 of 2 test cases) passed.
builder for ‘/nix/store/859ab0jjh7z2wrdjdzgch4sfjzmm018a-haskell-aws-0.12.1.drv’ failed with exit code 1
error: build of ‘/nix/store/859ab0jjh7z2wrdjdzgch4sfjzmm018a-haskell-aws-0.12.1.drv’ failed
```

**Comment by dmjio** [comment]
Here's a good mock server for `sqs`, we could use this. https://github.com/iain/fake_sqs.
For dynamo I highly recommend dynalite, I use it for all my local testing, the mock server given out by Amazon is very buggy.
https://github.com/mhart/dynalite

**Comment by aristidb** [comment]
I think for the time being it's best to disable the test suite under
Nixpkgs by default.

I'd be happy to take pull requests for running the tests against test/mock
servers though.

David Johnson <notifications@github.com> schrieb am Di., 11. Aug. 2015
21:50:
