### ISSUE TITLE
extend PutBucket for google nearline

### ISSUE THREAD

**Issue by joeyh** [aristidb/aws#182]
Google's nearline was discussed earlier in https://github.com/aristidb/aws/issues/155 , which was closed since StorageClass was extended to support nearline. However, it turns out that is not complete support for nearline. 

In particular, it seems that a bucket must be created in a special way to be used as a nearline bucket. Google Cloud Storage applies the storage class per-bucket rather than per-object.

There's a transcript here which shows a bucket created in the usual way, and then that PutObject with nearline StorageClass fails. http://git-annex.branchable.com/bugs/Support_non-default_storage_classes_with_Google_Cloud_Storage/#comment-31a065d354f8ed4c267caf236af3adfe

A sample bucket put request body from https://cloud.google.com/storage/docs/xml-api/put-bucket (XML API tab) follows:

    <CreateBucketConfiguration>
       <LocationConstraint>US</LocationConstraint>
       <StorageClass>NEARLINE</StorageClass>
    </CreateBucketConfiguration>

**Comment by joeyh** [comment]
I don't have the google account to test this, but my fork has an Examples/PutBucketNearLine.hs which uses it.

**Comment by aristidb** [comment]
@joeyh I also don't have a Google Cloud Storage account. Can you maybe refer me to the user who requested the feature for git-annex, so he can test it?

**Comment by joeyh** [comment]
Aristid Breitkreuz wrote:
> @joeyh I also don't have a Google Cloud Storage account. Can you maybe refer me
> to the user who requested the feature for git-annex, so he can test it?

Hey @bgilbert or @jlebar, we could use your help testing!

If you check out http://github.com/joeyh/aws , 
`cabal confgure -fExamples; cabal build` will create a test program in
`dist/build/PutBucketNearLine/PutBucketNearLine` ; it expects the usual
env vars for S3 creds, and you need to pass it the name of the bucket to
create.

If that works, and creates a usable nearline bucket, we can probably get it
merged into mainline aws and then get support in git-annex.

-- 
see shy jo

**Comment by jlebar** [comment]
$ ./PutBucketNearLine jlebar-joeyh-test-bucket
	Debug: String to sign: "PUT\n\n\nSat, 17 Oct 2015 20:05:12 GMT\n/jlebar-joeyh-test-bucket/"
	Debug: Host: "jlebar-joeyh-test-bucket.storage.googleapis.com"
	Debug: Path: "/"
	Debug: Query string: ""
	Debug: Body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><CreateBucketConfiguration xmlns=\"http://s3.amazonaws.com/doc/2006-03-01/\"><LocationConstraint>US</LocationConstraint><StorageClass xmlns=\"\">NEARLINE</StorageClass></CreateBucketConfiguration>"
	Debug: Response status: Status {statusCode = 200, statusMessage = "OK"}
	Debug: Response header 'X-GUploader-UploadID': 'AEnB2UpRmeCcp19byVBQ1sUhF6BsSr8u8t5M4TvQGTzmfBZdMZNpWFNuI8V0-N58xpWBy1FpVgAs_vDFjpxTNAyNNSNbZUBDqw'
	Debug: Response header 'x-goog-metageneration': '1'
	Debug: Response header 'Vary': 'Origin'
	Debug: Response header 'Content-Length': '0'
	Debug: Response header 'Date': 'Sat, 17 Oct 2015 20:05:14 GMT'
	Debug: Response header 'Server': 'UploadServer'
	Debug: Response header 'Content-Type': 'text/html; charset=UTF-8'
	Info: Response metadata: S3: request ID=<none>, x-amz-id-2=<none>
	PutBucketResponse

I checked in the console and the bucket is there and is configured to use nearline.
