### ISSUE TITLE
How do you generate pre-signed object URL (S3) with this library?

### ISSUE THREAD

**Issue by mrkkrp** [aristidb/aws#189]
Well, the title says it all.

**Comment by potomak** [comment]
I think you could generate a `GetObject` *request* by following the [example](https://github.com/aristidb/aws/blob/2947748c7d59a50363012aac48ee21adbbde20eb/Examples/GetObject.hs)

```haskell
let r = S3.getObject "haskell-aws" "cloud-remote.pdf"
```

and then follow the same process used by [`unsafeAwsRef`](https://hackage.haskell.org/package/aws-0.13.0/docs/Aws-Aws.html#v:unsafeAwsRef) to [sign the query](https://github.com/aristidb/aws/blob/2947748c7d59a50363012aac48ee21adbbde20eb/Aws/Aws.hs#L234-L237).

Note: I don't think this is a proper issue.

**Comment by mrkkrp** [comment]
Well, this is a question. Questions are proper issues also. Given full absence of documentation, I decided would I ask you directly. Closing.

**Comment by mrkkrp** [comment]
Sorry, I was wrong, some functions do have docs. However, how on the earth any user of the library should know where to look *in source code* to understand how to sign query?

**Comment by aristidb** [comment]
See the awsUri function: http://hackage.haskell.org/package/aws-0.13.0/docs/Aws-Aws.html#g:6

Given that @potomak suggested the wrong option, I guess the docs indeed could be clearer.

**Comment by aristidb** [comment]
Also, I'm not going to do "issue police" here, if somebody has a question they can also open an issue, as we don't really have a better venue for that right now. :-)

Please close this issue if the preceding comment about awsUri answers your question.

**Comment by mrkkrp** [comment]
@aristidb, Thanks, it works.

**Comment by potomak** [comment]
@aristidb @mrkkrp cool, I didn't know about that function, so yes, I guess there's room for improving the docs.

About issues, that was an opinion of mine, so no hard feelings.
