### ISSUE TITLE
Request: New release 0.13.1 for data-default 0.7

### ISSUE THREAD

**Issue by ilovezfs** [aristidb/aws#202]
Regarding, https://github.com/aristidb/aws/commit/402bfe5aa9ef4bec84186880faafcbfdae1ad91d, any chance of getting a 0.13.1 soon with this change in it (even if the release is just 0.13.0 + 402bfe5aa9ef4bec84186880faafcbfdae1ad91d)?

Right now this issue causes a stock cabal install of the current git-annex to lack S3 support, so for Homebrew we're now considering patching aws https://github.com/Homebrew/homebrew-core/pull/1307 to work around this issue.

**Comment by joeyh** [comment]
Does constraining the data-default version in git-annex.cabal to < 0.6 work around this problem?

**Comment by ilovezfs** [comment]
Indeed. And now data-default is at 0.7.

**Comment by ilovezfs** [comment]
@joeyh Also, I discovered the reason the `s3` flag wasn't getting solver to pick < 0.6 was due to a brew bug: https://github.com/Homebrew/brew/pull/267

**Comment by ilovezfs** [comment]
@felixonmars looks like 0.7 is fine too. Do you mind bumping the restriction from <0.7 to <0.8? Thanks!
Also, any blockers for a new a version?

**Comment by felixonmars** [comment]
I am not maintainer of the module, maybe you want to ask @aristidb :)

**Comment by aristidb** [comment]
I'm mostly just currently a bit short on free time, as I only do Haskell in
my spare time. :)

Felix Yan <notifications@github.com> schrieb am Di., 24. Mai 2016 um
07:10 Uhr:

**Comment by ilovezfs** [comment]
@aristidb Hi there, thanks for piping up. This is the context for the request: http://git-annex.branchable.com/bugs/ghc_8.0.1_build_fixes/

**Comment by ilovezfs** [comment]
So the main issues seem to be the restrictions on base, data-default, time, and transformers, of which the data-default, time, and transformers restrictions are specifically coming from aws.

**Comment by felixonmars** [comment]
Updated in #204

**Comment by ilovezfs** [comment]
@felixonmars nice

**Comment by bgamari** [comment]
@aristidb would it help if someone offered to help with maintenance? I personally rely on it for several projects and currently it does not build with GHC 8.0.1.

**Comment by aristidb** [comment]
@bgamari Yes, that would be great. I'll grant you commit privileges.

**Comment by aristidb** [comment]
@bgamari Please accept your Github collaboration invite if you're interested.

**Comment by aristidb** [comment]
0.13.1 is released.

@bgamari My offer of contributor rights stands, though.
