### ISSUE TITLE
S3 Object GET - Overriding Expires or Cache-Control headers is broken for presigned URLs

### ISSUE THREAD

**Issue by HanStolpo** [aristidb/aws#210]
With presigned URLs its not possible to override the `Expires` or `Cache-Control` HTTP headers on a Object GET request to control caching. This is because the signature generated when values are supplied to `goResponseExpires` or `goResponseCacheControl` is invalid. See pull request #209 which gives more detail and fixes the issue.

**Comment by aristidb** [comment]
Fixed with #209
