### ISSUE TITLE
aws not included to lts-8

### ISSUE THREAD

**Issue by rblaze** [aristidb/aws#224]
Just noticed aws is not included in lts-8.0 snapshot. Are there some compatibility issues? I'd really like to have recent version there.

**Comment by aristidb** [comment]
I think this is due to #218: http-client 0.5 made some breaking changes, which aws does not support yet. I'm happy to take pull requests to remedy this situation.

**Comment by juhp** [comment]
In current Stackage Nightly:

http-client-0.5.7.0 is out of bounds for:
- [ ] aws-0.16 (>=0.3 && < 0.5). No maintainer. @aristidb. Used by: test-suite

**Comment by aristidb** [comment]
aws 0.17 should fix this
