### ISSUE TITLE
Please support ghc-8.2.1 (by allowing time-1.8.*)

### ISSUE THREAD

**Issue by peti** [aristidb/aws#238]
There are a number of outdated dependencies in this package (http://packdeps.haskellers.com/feed?needle=exact%3Aaws), but the most relevant one is on `time` which is at version 1.8.0.2 in the latest GHC.

**Comment by ilovezfs** [comment]
@aristidb ping and hello again :)

**Comment by aristidb** [comment]
0.17 is released

**Comment by ilovezfs** [comment]
Thanks @aristidb!
