### ISSUE TITLE
PutBucket versioning

### ISSUE THREAD

**Issue by joeyh** [aristidb/aws#254]
aws already supports versioned objects, but it is not able to create a bucket with versioning enabled. https://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUTVersioningStatus.html is the API for that.

This would involve adding a new field to PutBucket, which could simply be "pbVersioningEnabled :: Bool"
and when it's enabled, add the neccessary XML to the request body.

If that seems like a reasonable design, I'll have a go at implementing it.

**Comment by aristidb** [comment]
Seems reasonable enough. Please have a go.

**Comment by joeyh** [comment]
I missed that PUT /?versioning  only works with an existing bucket; it cannot be used when creating a new bucket.

So, this will need to be part of a new module rather than PutBucket.

There is also a GET /?versioning that it will make sense to also add support for.
